-- MySQL Script generated by MySQL Workbench
-- Tue Jun 20 21:03:00 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bailao
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bailao` ;

-- -----------------------------------------------------
-- Schema bailao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bailao` DEFAULT CHARACTER SET utf8 ;
USE `bailao` ;

-- -----------------------------------------------------
-- Table `bailao`.`ENDERECO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bailao`.`ENDERECO` ;

CREATE TABLE IF NOT EXISTS `bailao`.`ENDERECO` (
  `idENDERECO` INT NOT NULL,
  `logradouroEndereco` VARCHAR(20) NULL,
  `nomeEndereco` VARCHAR(100) NULL,
  `numeroEndereco` VARCHAR(6) NULL,
  PRIMARY KEY (`idENDERECO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bailao`.`Gravadora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bailao`.`Gravadora` ;

CREATE TABLE IF NOT EXISTS `bailao`.`Gravadora` (
  `CNPJ` VARCHAR(14) NOT NULL,
  `razao_social` VARCHAR(100) NOT NULL,
  `teleofnes_contato` VARCHAR(45) NOT NULL,
  `endereco` TEXT NULL,
  `ENDERECO_idENDERECO` INT NOT NULL,
  PRIMARY KEY (`CNPJ`),
  INDEX `fk_Gravadora_ENDERECO1_idx` (`ENDERECO_idENDERECO` ASC) VISIBLE,
  CONSTRAINT `fk_Gravadora_ENDERECO1`
    FOREIGN KEY (`ENDERECO_idENDERECO`)
    REFERENCES `bailao`.`ENDERECO` (`idENDERECO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bailao`.`CIDADE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bailao`.`CIDADE` ;

CREATE TABLE IF NOT EXISTS `bailao`.`CIDADE` (
  `idCidade` INT NOT NULL,
  `nomeCidade` VARCHAR(100) NULL,
  PRIMARY KEY (`idCidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bailao`.`BANDA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bailao`.`BANDA` ;

CREATE TABLE IF NOT EXISTS `bailao`.`BANDA` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `ano_criacao` INT NOT NULL,
  `CIDADE_idCidade` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_BANDA_CIDADE1_idx` (`CIDADE_idCidade` ASC) VISIBLE,
  CONSTRAINT `fk_BANDA_CIDADE1`
    FOREIGN KEY (`CIDADE_idCidade`)
    REFERENCES `bailao`.`CIDADE` (`idCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bailao`.`Album`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bailao`.`Album` ;

CREATE TABLE IF NOT EXISTS `bailao`.`Album` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `data_lancamento` DATE NOT NULL,
  `midia` VARCHAR(50) NULL COMMENT 'Pode ser: CD, DVD ou Streamming',
  `Gravadora_CNPJ` VARCHAR(14) NULL,
  `BANDA_id` INT NOT NULL,
  PRIMARY KEY (`id`, `BANDA_id`),
  INDEX `fk_Album_Gravadora_idx` (`Gravadora_CNPJ` ASC) VISIBLE,
  INDEX `fk_Album_BANDA1_idx` (`BANDA_id` ASC) VISIBLE,
  CONSTRAINT `fk_Album_Gravadora`
    FOREIGN KEY (`Gravadora_CNPJ`)
    REFERENCES `bailao`.`Gravadora` (`CNPJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Album_BANDA1`
    FOREIGN KEY (`BANDA_id`)
    REFERENCES `bailao`.`BANDA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bailao`.`MUSICOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bailao`.`MUSICOS` ;

CREATE TABLE IF NOT EXISTS `bailao`.`MUSICOS` (
  `idMusicos` INT NOT NULL,
  `nomeMusico` VARCHAR(100) NULL,
  PRIMARY KEY (`idMusicos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bailao`.`MUSICOS_compoem_BANDA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bailao`.`MUSICOS_compoem_BANDA` ;

CREATE TABLE IF NOT EXISTS `bailao`.`MUSICOS_compoem_BANDA` (
  `MUSICOS_idMusicos` INT NOT NULL,
  `BANDA_id` INT NOT NULL,
  PRIMARY KEY (`MUSICOS_idMusicos`, `BANDA_id`),
  INDEX `fk_MUSICOS_has_BANDA_BANDA1_idx` (`BANDA_id` ASC) VISIBLE,
  INDEX `fk_MUSICOS_has_BANDA_MUSICOS1_idx` (`MUSICOS_idMusicos` ASC) VISIBLE,
  CONSTRAINT `fk_MUSICOS_has_BANDA_MUSICOS1`
    FOREIGN KEY (`MUSICOS_idMusicos`)
    REFERENCES `bailao`.`MUSICOS` (`idMusicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MUSICOS_has_BANDA_BANDA1`
    FOREIGN KEY (`BANDA_id`)
    REFERENCES `bailao`.`BANDA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bailao`.`TELEFONE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bailao`.`TELEFONE` ;

CREATE TABLE IF NOT EXISTS `bailao`.`TELEFONE` (
  `numero` VARCHAR(9) NOT NULL,
  `Gravadora_CNPJ` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`numero`, `Gravadora_CNPJ`),
  INDEX `fk_TELEFONE_Gravadora1_idx` (`Gravadora_CNPJ` ASC) VISIBLE,
  CONSTRAINT `fk_TELEFONE_Gravadora1`
    FOREIGN KEY (`Gravadora_CNPJ`)
    REFERENCES `bailao`.`Gravadora` (`CNPJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
