package classes;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author v3gc
 */
public class telaSuperCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form TelaSuperCalculadora
     */
    public telaSuperCalculadora() {
        initComponents();
        panCalculadora.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        txtValor = new javax.swing.JSpinner();
        panCalculadora = new javax.swing.JPanel();
        lblRaizQuadrada = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblRaizCubica = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblValorAbsoluto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblModuloPor2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblValorAoCubo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Super Calculadora");

        jLabel2.setText("Informe um valor:");

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        lblRaizQuadrada.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        lblRaizQuadrada.setForeground(new java.awt.Color(0, 204, 204));
        lblRaizQuadrada.setText("0");

        jLabel9.setText("Raiz Cúbica");

        lblRaizCubica.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        lblRaizCubica.setForeground(new java.awt.Color(0, 204, 204));
        lblRaizCubica.setText("0");

        jLabel11.setText("Valor Absoluto");

        lblValorAbsoluto.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        lblValorAbsoluto.setForeground(new java.awt.Color(0, 204, 204));
        lblValorAbsoluto.setText("0");

        jLabel3.setText("Resto da Divisão por 2");

        lblModuloPor2.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        lblModuloPor2.setForeground(new java.awt.Color(0, 204, 204));
        lblModuloPor2.setText("0");

        jLabel5.setText("Elevado ao Cubo");

        lblValorAoCubo.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        lblValorAoCubo.setForeground(new java.awt.Color(0, 204, 204));
        lblValorAoCubo.setText("0");

        jLabel7.setText("Raiz Quadrada");

        javax.swing.GroupLayout panCalculadoraLayout = new javax.swing.GroupLayout(panCalculadora);
        panCalculadora.setLayout(panCalculadoraLayout);
        panCalculadoraLayout.setHorizontalGroup(
            panCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCalculadoraLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(panCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panCalculadoraLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblValorAbsoluto))
                    .addGroup(panCalculadoraLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblValorAoCubo, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panCalculadoraLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRaizCubica))
                    .addGroup(panCalculadoraLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRaizQuadrada))
                    .addGroup(panCalculadoraLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblModuloPor2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panCalculadoraLayout.setVerticalGroup(
            panCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCalculadoraLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblModuloPor2))
                .addGap(18, 18, 18)
                .addGroup(panCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblValorAoCubo))
                .addGap(18, 18, 18)
                .addGroup(panCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblRaizQuadrada))
                .addGap(18, 18, 18)
                .addGroup(panCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblRaizCubica))
                .addGap(18, 18, 18)
                .addGroup(panCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblValorAbsoluto))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCalcular)
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panCalculadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panCalculadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        int valor = Integer.parseInt(txtValor.getValue().toString());
        
        int moduloPor2 = valor%2;
        lblModuloPor2.setText(Integer.toString(moduloPor2));
        
        double aoCubo = Math.pow(valor,3);
        lblValorAoCubo.setText(Double.toString(aoCubo));
        
        double raizQuadrada = Math.sqrt(valor);
        lblRaizQuadrada.setText(String.format("%.2f",raizQuadrada));
        
        double raizCubica = Math.cbrt(valor);
        lblRaizCubica.setText(String.format("%.2f",raizCubica));
        
        int valorAbsoluto = Math.abs(valor);
        lblValorAbsoluto.setText(Integer.toString(valorAbsoluto));
        
        panCalculadora.setVisible(true);
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaSuperCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaSuperCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaSuperCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaSuperCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaSuperCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblModuloPor2;
    private javax.swing.JLabel lblRaizCubica;
    private javax.swing.JLabel lblRaizQuadrada;
    private javax.swing.JLabel lblValorAbsoluto;
    private javax.swing.JLabel lblValorAoCubo;
    private javax.swing.JPanel panCalculadora;
    private javax.swing.JSpinner txtValor;
    // End of variables declaration//GEN-END:variables
}
